gRPCserver:
  host: "localhost"
  port: "8080"
  linkLength: 10

HTTPserver:
  host: "0.0.0.0"
  port: "8000"
  linkLength: 10

db:
  host: "localhost"
  port: "5432"
  username: "postgres"
  password: "admin"
  dbname: "postgres"
  sslmode: "disable"
  format: false