// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.0
// source: service.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LinkShortenerClient is the client API for LinkShortener service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LinkShortenerClient interface {
	PutUrl(ctx context.Context, in *Link, opts ...grpc.CallOption) (*Link, error)
	GetUrl(ctx context.Context, in *Link, opts ...grpc.CallOption) (*Link, error)
}

type linkShortenerClient struct {
	cc grpc.ClientConnInterface
}

func NewLinkShortenerClient(cc grpc.ClientConnInterface) LinkShortenerClient {
	return &linkShortenerClient{cc}
}

func (c *linkShortenerClient) PutUrl(ctx context.Context, in *Link, opts ...grpc.CallOption) (*Link, error) {
	out := new(Link)
	err := c.cc.Invoke(ctx, "/pb.LinkShortener/PutUrl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkShortenerClient) GetUrl(ctx context.Context, in *Link, opts ...grpc.CallOption) (*Link, error) {
	out := new(Link)
	err := c.cc.Invoke(ctx, "/pb.LinkShortener/GetUrl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LinkShortenerServer is the server API for LinkShortener service.
// All implementations must embed UnimplementedLinkShortenerServer
// for forward compatibility
type LinkShortenerServer interface {
	PutUrl(context.Context, *Link) (*Link, error)
	GetUrl(context.Context, *Link) (*Link, error)
	mustEmbedUnimplementedLinkShortenerServer()
}

// UnimplementedLinkShortenerServer must be embedded to have forward compatible implementations.
type UnimplementedLinkShortenerServer struct {
}

func (UnimplementedLinkShortenerServer) PutUrl(context.Context, *Link) (*Link, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutUrl not implemented")
}
func (UnimplementedLinkShortenerServer) GetUrl(context.Context, *Link) (*Link, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUrl not implemented")
}
func (UnimplementedLinkShortenerServer) mustEmbedUnimplementedLinkShortenerServer() {}

// UnsafeLinkShortenerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LinkShortenerServer will
// result in compilation errors.
type UnsafeLinkShortenerServer interface {
	mustEmbedUnimplementedLinkShortenerServer()
}

func RegisterLinkShortenerServer(s grpc.ServiceRegistrar, srv LinkShortenerServer) {
	s.RegisterService(&LinkShortener_ServiceDesc, srv)
}

func _LinkShortener_PutUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Link)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkShortenerServer).PutUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LinkShortener/PutUrl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkShortenerServer).PutUrl(ctx, req.(*Link))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinkShortener_GetUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Link)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkShortenerServer).GetUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LinkShortener/GetUrl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkShortenerServer).GetUrl(ctx, req.(*Link))
	}
	return interceptor(ctx, in, info, handler)
}

// LinkShortener_ServiceDesc is the grpc.ServiceDesc for LinkShortener service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LinkShortener_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.LinkShortener",
	HandlerType: (*LinkShortenerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutUrl",
			Handler:    _LinkShortener_PutUrl_Handler,
		},
		{
			MethodName: "GetUrl",
			Handler:    _LinkShortener_GetUrl_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
